export const GET_CUSTOMER = 'GET_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const SET_PAGE_CUSTOMER = 'SET_PAGE_CUSTOMER';
export const SEARCH_CUSTOMER_BY_SDT = 'SEARCH_CUSTOMER_BY_SDT';
